[project]
name = "restaurant-ordering-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Isaac Urban", email = "kpomassiurban@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
restaurant-ordering-system = "restaurant_ordering_system:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
